### ISSUE TITLE
The Material Ripple Consumes Clicks

### ISSUE THREAD

**Issue by gauntface** [google/web-starter-kit#625] opened 2015-02-03 01:14 UTC
Kinlan realised that using the ripple will consume the click event on a button.

**Comment by sgomes** [comment] 2015-02-06 17:32
@gauntface Can't reproduce, buttons seem to be working fine for me in Chrome, IE and Firefox. Could you provide more details?

**Comment by gauntface** [comment] 2015-02-06 17:34
@paulkinlan can you provide code that reproduces please.

**Comment by sgomes** [comment] 2015-03-12 17:22
Closing. Feel free to reopen if it turns out this is still an issue.

**Closed by sgomes** 2015-03-12 17:22 UTC
