### ISSUE TITLE
when gulp serve: events.js:85 throw er; // Unhandled 'error' event

### ISSUE THREAD

**Issue by HansS** [google/web-starter-kit#678] opened 2015-04-29 07:40 UTC
C:\Users\Hans\web\starter\webstarterkit-1>gulp serve
[09:35:45] Using gulpfile ~\web\starter\webstarterkit-1\gulpfile.js
[09:35:45] Starting 'styles'...
[09:36:01] 'styles' all files 92.75 kB
[09:36:01] Finished 'styles' after 15 s
[09:36:01] Starting 'serve'...
[09:36:02] Finished 'serve' after 916 ms
[WSK] Local URL: http://localhost:3000
[WSK] External URL: http://192.168.178.21:3000
[WSK] Serving files from: .tmp
[WSK] Serving files from: app
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: spawn cmd ENOENT
    at exports._errnoException (util.js:746:11)
    at Process.ChildProcess._handle.onexit (child_process.js:1046:32)
    at child_process.js:1137:20
    at process._tickCallback (node.js:355:11)

C:\Users\Hans\web\starter\webstarterkit-1>node -v
v0.12.0

C:\Users\Hans\web\starter\webstarterkit-1>npm -v
2.5.1

**Comment by ohyouknowwho** [comment] 2015-05-01 22:53
Are you on the latest version of wsk? This looks like #649

**Comment by addyosmani** [comment] 2015-05-03 17:52
If you could verify this issue against the latest version in Master that would help us nail down the cause of this.

**Comment by codeandrop** [comment] 2015-05-03 23:00
I tested the following config:  Windows 8.1, node 0.12.2, npm 2.7.4, gulp 3.8.11 

After following installation instructions, ran gulp serve and modified some components files it worked (no error event)
 
@addyosmani I think you can close this issue

**Comment by HansS** [comment] 2015-05-04 07:05
Webstarter Kit install step 1:
------------------------------------------------------------------------------------
C:\Users\Hans\web\google\wsk_054>npm i
\


> ws@0.5.0 install C:\Users\Hans\web\google\wsk_054\node_modules\browser-sync\node_modules\socket.io\node_modules\engine.io\node_modules\ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

/
C:\Users\Hans\web\google\wsk_054\node_modules\browser-sync\node_modules\socket.io\node_modules\engine.io\node_modules\ws>node "C:\Users\Hans\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild
\
> phantomjs@1.9.16 install C:\Users\Hans\web\google\wsk_054\node_modules\gulp-uncss\node_modules\uncss\node_modules\phridge\node_modules\phantomjs
> node install.js

PhantomJS detected, but wrong version 1.9.1 @ C:\Users\Hans\AppData\Roaming\PhantomJs\phantomjs-1.9.1-windows\phantomjs.EXE.
Download already available at C:\Users\Hans\AppData\Local\Temp\phantomjs\phantomjs-1.9.8-windows.zip
Extracting zip contents
Removing C:\Users\Hans\web\google\wsk_054\node_modules\gulp-uncss\node_modules\uncss\node_modules\phridge\node_modules\phantomjs\lib\phantom
Copying extracted folder C:\Users\Hans\AppData\Local\Temp\phantomjs\phantomjs-1.9.8-windows.zip-extract-1430722380412\phantomjs-1.9.8-windows -> C:\Users\Hans\web\google\wsk_054\node_modules\gulp-uncss\node_modules\uncss\node_modules\phridge\node_modules\phantomjs\lib\phantom
Writing location.js file
Done. Phantomjs binary available at C:\Users\Hans\web\google\wsk_054\node_modules\gulp-uncss\node_modules\uncss\node_modules\phridge\node_modules\phantomjs\lib\phantom\phantomjs.exe
npm WARN deprecated jws@0.0.2: Security update: Versions below 3.0.0 are deprecated.
npm WARN deprecated tap-consumer@0.0.1: This module is not supported. Please use 'tap' instead.
npm WARN deprecated tap-results@0.0.2: This module is not supported. Please use 'tap' instead.

> ws@0.4.31 install C:\Users\Hans\web\google\wsk_054\node_modules\browser-sync\node_modules\socket.io\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)


C:\Users\Hans\web\google\wsk_054\node_modules\browser-sync\node_modules\socket.io\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws>node "C:\Users\Hans\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild

> optipng-bin@2.0.4 postinstall C:\Users\Hans\web\google\wsk_054\node_modules\gulp-imagemin\node_modules\imagemin\node_modules\imagemin-optipng\node_modules\optipng-bin
> node lib/install.js

  √ optipng pre-build test passed successfully

> gifsicle@2.0.1 postinstall C:\Users\Hans\web\google\wsk_054\node_modules\gulp-imagemin\node_modules\imagemin\node_modules\imagemin-gifsicle\node_modules\gifsicle
> node lib/install.js

  √ gifsicle pre-build test passed successfully


> pngquant-bin@3.0.0 postinstall C:\Users\Hans\web\google\wsk_054\node_modules\gulp-imagemin\node_modules\imagemin\node_modules\imagemin-pngquant\node_modules\pngquant-bin
> node lib/install.js

  √ pngquant pre-build test passed successfully

> jpegtran-bin@2.0.2 postinstall C:\Users\Hans\web\google\wsk_054\node_modules\gulp-imagemin\node_modules\imagemin\node_modules\imagemin-jpegtran\node_modules\jpegtran-bin
> node lib/install.js

  √ jpegtran pre-build test passed successfully

> node-sass@2.1.1 install C:\Users\Hans\web\google\wsk_054\node_modules\gulp-sass\node_modules\node-sass
> node scripts/install.js


> node-sass@2.1.1 postinstall C:\Users\Hans\web\google\wsk_054\node_modules\gulp-sass\node_modules\node-sass
> node scripts/build.js

`win32-ia32-node-0.12` exists; testing
Binary is fine; exiting
opn@1.0.2 node_modules\opn

apache-server-configs@2.14.0 node_modules\apache-server-configs

require-dir@0.1.0 node_modules\require-dir

jshint-stylish@1.0.2 node_modules\jshint-stylish
├── log-symbols@1.0.2
├── text-table@0.2.0
├── string-length@1.0.0 (strip-ansi@2.0.1)
└── chalk@1.0.0 (escape-string-regexp@1.0.3, ansi-styles@2.0.1, supports-color@1.3.1, strip-ansi@2.0.1, has-ansi@1.0.3)

run-sequence@1.1.0 node_modules\run-sequence
└── chalk@1.0.0 (escape-string-regexp@1.0.3, ansi-styles@2.0.1, supports-color@1.3.1, strip-ansi@2.0.1, has-ansi@1.0.3)

gulp-sourcemaps@1.5.2 node_modules\gulp-sourcemaps
├── graceful-fs@3.0.6
├── convert-source-map@1.1.0
├── strip-bom@1.0.0 (first-chunk-stream@1.0.0, is-utf8@0.2.0)
├── vinyl@0.4.6 (clone-stats@0.0.1, clone@0.2.0)
└── through2@0.6.5 (xtend@4.0.0, readable-stream@1.0.33)

gulp-replace@0.5.3 node_modules\gulp-replace
├── istextorbinary@1.0.2 (binaryextensions@1.0.0, textextensions@1.0.1)
├── replacestream@2.0.0 (through@2.3.7)
└── through2@0.6.3 (xtend@4.0.0, readable-stream@1.0.33)

gulp-load-plugins@0.8.1 node_modules\gulp-load-plugins
├── multimatch@2.0.0 (array-differ@1.0.0, array-union@1.0.1, minimatch@2.0.7)
└── findup-sync@0.2.1 (glob@4.3.5)

del@1.1.1 node_modules\del
├── is-path-cwd@1.0.0
├── object-assign@2.0.0
├── each-async@1.1.1 (set-immediate-shim@1.0.1, onetime@1.0.0)
├── is-path-in-cwd@1.0.0 (is-path-inside@1.0.0)
├── globby@1.2.0 (array-union@1.0.1, async@0.9.0, glob@4.5.3)
└── rimraf@2.3.3 (glob@4.5.3)

gulp-if@1.2.5 node_modules\gulp-if
├── through2@0.6.5 (xtend@4.0.0, readable-stream@1.0.33)
├── gulp-match@0.2.1 (minimatch@1.0.0)
└── ternary-stream@1.2.3 (merge-stream@0.1.7, fork-stream@0.0.4, duplexer2@0.0.2)

gulp-changed@1.2.1 node_modules\gulp-changed
├── through2@0.6.5 (xtend@4.0.0, readable-stream@1.0.33)
└── gulp-util@3.0.4 (array-differ@1.0.0, object-assign@2.0.0, beeper@1.0.0, array-uniq@1.0.2, lodash._reinterpolate@3.0.0, lodash._reevaluate@3.0.0, lodash._reescape@3.0.0, replace-ext@0.0.1, minimist@1.1.1, vinyl@0.4.6, chalk@1.0.0, lodash.template@3.5.1, dateformat@1.0.11, multipipe@0.1.2)

gulp-flatten@0.0.4 node_modules\gulp-flatten
├── through2@0.6.5 (xtend@4.0.0, readable-stream@1.0.33)
└── gulp-util@3.0.4 (array-differ@1.0.0, object-assign@2.0.0, beeper@1.0.0, array-uniq@1.0.2, lodash._reinterpolate@3.0.0, lodash._reescape@3.0.0, lodash._reevaluate@3.0.0, replace-ext@0.0.1, minimist@1.1.1, vinyl@0.4.6, chalk@1.0.0, lodash.template@3.5.1, dateformat@1.0.11, multipipe@0.1.2)

gulp-minify-html@0.1.5 node_modules\gulp-minify-html
├── through2@0.5.1 (xtend@3.0.0, readable-stream@1.0.33)
├── gulp-util@2.2.20 (lodash._reinterpolate@2.4.1, minimist@0.2.0, chalk@0.5.1, vinyl@0.2.3, lodash.template@2.4.1, dateformat@1.0.11, multipipe@0.1.2)

└── minimize@0.8.2 (utile@0.2.1, htmlparser2@3.7.3)

gulp@3.8.11 node_modules\gulp
├── pretty-hrtime@0.2.2
├── interpret@0.3.10
├── deprecated@0.0.1
├── archy@1.0.0
├── tildify@1.0.0 (user-home@1.1.1)
├── v8flags@2.0.5 (user-home@1.1.1)
├── minimist@1.1.1
├── chalk@0.5.1 (ansi-styles@1.1.0, escape-string-regexp@1.0.3, supports-color@0.2.0, strip-ansi@0.3.0, has-ansi@0.1.0)
├── orchestrator@0.3.7 (stream-consume@0.1.0, sequencify@0.0.7, end-of-stream@0.1.5)
├── semver@4.3.3
├── gulp-util@3.0.4 (array-differ@1.0.0, object-assign@2.0.0, beeper@1.0.0, array-uniq@1.0.2, lodash._reinterpolate@3.0.0, lodash._reevaluate@3.0.0, lodash._reescape@3.0.0, replace-ext@0.0.1, vinyl@0.4.6, chalk@1.0.0, lodash.template@3.5.1, through2@0.6.5, dateformat@1.0.11, multipipe@0.1.2)
├── liftoff@2.0.3 (extend@2.0.1, flagged-respawn@0.3.1, resolve@1.1.6, findup-sync@0.2.1)
└── vinyl-fs@0.3.13 (graceful-fs@3.0.6, strip-bom@1.0.0, defaults@1.0.2, vinyl@0.4.6, mkdirp@0.5.0, through2@0.6.5, glob-stream@3.1.18, glob-watcher@0.0.6)

gulp-size@1.2.1 node_modules\gulp-size
├── chalk@1.0.0 (escape-string-regexp@1.0.3, ansi-styles@2.0.1, supports-color@1.3.1, strip-ansi@2.0.1, has-ansi@1.0.3)
├── through2@0.6.5 (xtend@4.0.0, readable-stream@1.0.33)
├── pretty-bytes@1.0.4 (get-stdin@4.0.1, meow@3.1.0)
├── gulp-util@3.0.4 (array-differ@1.0.0, object-assign@2.0.0, beeper@1.0.0, array-uniq@1.0.2, lodash._reinterpolate@3.0.0, lodash._reevaluate@3.0.0, lodash._reescape@3.0.0, replace-ext@0.0.1, minimist@1.1.1, vinyl@0.4.6, lodash.template@3.5.1, dateformat@1.0.11, multipipe@0.1.2)
└── gzip-size@1.0.0 (concat-stream@1.4.8, browserify-zlib@0.1.4)

gulp-uglify@1.2.0 node_modules\gulp-uglify
├── deap@1.0.0
├── through2@0.6.5 (xtend@4.0.0, readable-stream@1.0.33)
├── gulp-util@3.0.4 (array-differ@1.0.0, beeper@1.0.0, object-assign@2.0.0, array-uniq@1.0.2, lodash._reevaluate@3.0.0, lodash._reinterpolate@3.0.0, lodash._reescape@3.0.0, replace-ext@0.0.1, minimist@1.1.1, vinyl@0.4.6, chalk@1.0.0, lodash.template@3.5.1, dateformat@1.0.11, multipipe@0.1.2)
├── vinyl-sourcemaps-apply@0.1.4 (source-map@0.1.43)
└── uglify-js@2.4.19 (uglify-to-browserify@1.0.2, async@0.2.10, yargs@3.5.4, source-map@0.1.34)

gulp-cache@0.2.2 node_modules\gulp-cache
├── map-stream@0.1.0
├── gulp-util@3.0.4 (array-differ@1.0.0, object-assign@2.0.0, beeper@1.0.0, array-uniq@1.0.2, lodash._reinterpolate@3.0.0, lodash._reevaluate@3.0.0, lodash._reescape@3.0.0, replace-ext@0.0.1, minimist@1.1.1, vinyl@0.4.6, chalk@1.0.0, lodash.template@3.5.1, through2@0.6.5, dateformat@1.0.11, multipipe@0.1.2)
├── bluebird@2.9.25
├── cache-swap@0.0.6 (async@0.2.10, rimraf@2.1.4, lodash@1.1.1)
└── lodash-node@2.4.1

gulp-useref@1.1.2 node_modules\gulp-useref
├── is-relative-url@1.0.0 (is-absolute-url@1.0.0)
├── brace-expansion@1.1.0 (concat-map@0.0.1, balanced-match@0.2.0)
├── node-useref@0.3.11
├── through2@0.6.5 (xtend@4.0.0, readable-stream@1.0.33)
├── gulp-util@3.0.4 (array-differ@1.0.0, object-assign@2.0.0, beeper@1.0.0, array-uniq@1.0.2, lodash._reinterpolate@3.0.0, lodash._reevaluate@3.0.0, lodash._reescape@3.0.0, replace-ext@0.0.1, minimist@1.1.1, vinyl@0.4.6, chalk@1.0.0, lodash.template@3.5.1, dateformat@1.0.11, multipipe@0.1.2)
├── gulp-concat@2.5.2 (concat-with-sourcemaps@1.0.2)
├── lodash@3.8.0
└── vinyl-fs@1.0.0 (object-assign@2.0.0, merge-stream@0.1.7, graceful-fs@3.0.6, strip-bom@1.0.0, vinyl@0.4.6, mkdirp@0.5.0, duplexify@3.3.0, glob-watcher@0.0.8, glob-stream@4.1.1)

gulp-jshint@1.10.0 node_modules\gulp-jshint
├── through2@0.6.5 (xtend@4.0.0, readable-stream@1.0.33)
├── minimatch@2.0.7 (brace-expansion@1.1.0)
├── gulp-util@3.0.4 (array-differ@1.0.0, beeper@1.0.0, object-assign@2.0.0, array-uniq@1.0.2, lodash._reinterpolate@3.0.0, lodash._reevaluate@3.0.0, lodash._reescape@3.0.0, replace-ext@0.0.1, minimist@1.1.1, vinyl@0.4.6, chalk@1.0.0, lodash.template@3.5.1, dateformat@1.0.11, multipipe@0.1.2)
├── rcloader@0.1.2 (rcfinder@0.1.8, lodash@2.4.2)
├── lodash@3.8.0
└── jshint@2.7.0 (strip-json-comments@1.0.2, exit@0.1.2, shelljs@0.3.0, console-browserify@1.1.0, cli@0.6.6, htmlparser2@3.8.2, lodash@3.6.0)

gulp-autoprefixer@2.2.0 node_modules\gulp-autoprefixer
├── object-assign@2.0.0
├── through2@0.6.5 (xtend@4.0.0, readable-stream@1.0.33)
├── gulp-util@3.0.4 (array-differ@1.0.0, beeper@1.0.0, array-uniq@1.0.2, lodash._reinterpolate@3.0.0, lodash._reescape@3.0.0, lodash._reevaluate@3.0.0, replace-ext@0.0.1, minimist@1.1.1, vinyl@0.4.6, chalk@1.0.0, lodash.template@3.5.1, dateformat@1.0.11, multipipe@0.1.2)
├── vinyl-sourcemaps-apply@0.1.4 (source-map@0.1.43)
├── postcss@4.1.8 (js-base64@2.1.8, source-map@0.4.2, es6-promise@2.1.1)
└── autoprefixer-core@5.1.11 (num2fraction@1.1.0, browserslist@0.2.0, postcss@4.0.6, caniuse-db@1.0.30000156)

gulp-csso@1.0.0 node_modules\gulp-csso
├── gulp-util@3.0.4 (array-differ@1.0.0, object-assign@2.0.0, beeper@1.0.0, array-uniq@1.0.2, lodash._reinterpolate@3.0.0, lodash._reescape@3.0.0, lodash._reevaluate@3.0.0, replace-ext@0.0.1, minimist@1.1.1, vinyl@0.4.6, chalk@1.0.0, lodash.template@3.5.1, through2@0.6.5, dateformat@1.0.11, multipipe@0.1.2)
└── csso@1.3.11

psi@1.0.6 node_modules\psi
├── object-assign@2.0.0
├── prepend-http@1.0.1
├── pretty-bytes@1.0.4 (get-stdin@4.0.1)
├── repeating@1.1.2 (is-finite@1.0.0)
├── sort-on@1.2.0 (dot-prop@2.0.0)
├── humanize-url@1.0.1 (strip-url-auth@1.0.0, normalize-url@1.2.0)
├── chalk@1.0.0 (escape-string-regexp@1.0.3, ansi-styles@2.0.1, supports-color@1.3.1, strip-ansi@2.0.1, has-ansi@1.0.3)
├── meow@3.1.0 (camelcase-keys@1.0.0, indent-string@1.2.1, minimist@1.1.1)
├── update-notifier@0.3.2 (is-npm@1.0.0, string-length@1.0.0, semver-diff@2.0.0, latest-version@1.0.0, configstore@0.3.2)
├── lodash@3.8.0
└── googleapis@1.1.5 (async@0.9.0, string-template@0.2.0, request@2.51.0, gapitoken@0.1.4)

browser-sync@1.9.2 node_modules\browser-sync
├── emitter-steward@0.0.1
├── opt-merger@1.1.0
├── easy-extender@2.3.1
├── object-path@0.8.1
├── minimist@1.1.1
├── commander@2.8.1 (graceful-readlink@1.0.1)
├── tfunk@3.0.1 (object-path@0.9.2, chalk@0.5.1)
├── ua-parser-js@0.7.7
├── browser-sync-client@1.0.2
├── connect@3.3.5 (utils-merge@1.0.0, parseurl@1.3.0, debug@2.1.3, finalhandler@0.3.4)
├── serve-static@1.9.2 (utils-merge@1.0.0, escape-html@1.0.1, parseurl@1.3.0, send@0.12.2)
├── resp-modifier@1.0.2 (minimatch@2.0.7)
├── portscanner-plus@0.2.1 (q@1.3.0, portscanner@1.0.0)
├── foxy@7.1.0 (cookie@0.1.2, dev-ip@1.0.1, http-proxy@1.11.1, meow@2.1.0, immutable@3.7.2)
├── serve-index@1.6.3 (escape-html@1.0.1, parseurl@1.3.0, batch@0.5.2, http-errors@1.3.1, accepts@1.2.5, debug@2.1.3, mime-types@2.0.10)
├── glob-watcher@0.0.7 (gaze@0.5.1)
├── lodash@2.4.2
├── dev-ip@0.1.7 (lodash@2.2.1)
├── localtunnel@1.5.0 (debug@0.7.4, optimist@0.3.4, request@2.11.4)
├── eazy-logger@2.1.2 (lodash@3.8.0)
└── socket.io@1.3.5 (debug@2.1.0, has-binary-data@0.1.3, socket.io-adapter@0.3.1, engine.io@1.5.1, socket.io-parser@2.2.4, socket.io-client@1.3.5)

gulp-uncss@1.0.1 node_modules\gulp-uncss
├── object-assign@2.0.0
├── gulp-util@3.0.4 (array-differ@1.0.0, beeper@1.0.0, array-uniq@1.0.2, lodash._reevaluate@3.0.0, lodash._reescape@3.0.0, lodash._reinterpolate@3.0.0, replace-ext@0.0.1, minimist@1.1.1, vinyl@0.4.6, chalk@1.0.0, lodash.template@3.5.1, through2@0.6.5, dateformat@1.0.11, multipipe@0.1.2)
└── uncss@0.12.1 (is-absolute-url@1.0.0, commander@2.6.0, is-html@1.0.0, glob@4.4.2, css@1.6.0, bluebird@2.9.25, request@2.53.0, lodash@3.3.1, phridge@1.0.8)

gulp-imagemin@2.2.1 node_modules\gulp-imagemin
├── object-assign@2.0.0
├── chalk@1.0.0 (escape-string-regexp@1.0.3, ansi-styles@2.0.1, supports-color@1.3.1, strip-ansi@2.0.1, has-ansi@1.0.3)
├── pretty-bytes@1.0.4 (get-stdin@4.0.1, meow@3.1.0)
├── through2-concurrent@0.3.1 (through2@0.6.5)
├── gulp-util@3.0.4 (array-differ@1.0.0, beeper@1.0.0, array-uniq@1.0.2, lodash._reinterpolate@3.0.0, lodash._reevaluate@3.0.0, lodash._reescape@3.0.0, replace-ext@0.0.1, minimist@1.1.1, vinyl@0.4.6, lodash.template@3.5.1, through2@0.6.5, dateformat@1.0.11, multipipe@0.1.2)
└── imagemin@3.1.0 (get-stdin@3.0.2, optional@0.1.3, vinyl@0.4.6, stream-combiner@0.2.1, meow@2.1.0, through2@0.6.5, concat-stream@1.4.8, vinyl-fs@0.3.13, imagemin-svgo@4.1.2, imagemin-optipng@4.2.0, imagemin-gifsicle@4.1.0, imagemin-pngquant@4.1.0, imagemin-jpegtran@4.1.0)

gulp-sass@1.3.3 node_modules\gulp-sass
├── clone@0.1.19
├── map-stream@0.1.0
├── gulp-util@3.0.4 (array-differ@1.0.0, beeper@1.0.0, object-assign@2.0.0, array-uniq@1.0.2, lodash._reevaluate@3.0.0, lodash._reinterpolate@3.0.0, lodash._reescape@3.0.0, replace-ext@0.0.1, minimist@1.1.1, vinyl@0.4.6, chalk@1.0.0, lodash.template@3.5.1, through2@0.6.5, dateformat@1.0.11, multipipe@0.1.2)
├── vinyl-sourcemaps-apply@0.1.4 (source-map@0.1.43)
└── node-sass@2.1.1 (object-assign@2.0.0, get-stdin@4.0.1, replace-ext@0.0.1, cross-spawn@0.2.9, chalk@0.5.1, mkdirp@0.5.0, nan@1.8.4, shelljs@0.3.0, semver@4.3.3, meow@3.1.0, npmconf@2.1.1, gaze@0.5.1, sass-graph@1.3.0, request@2.55.0, mocha@2.2.4, pangyp@2.1.0)

C:\Users\Hans\web\google\wsk_054>

Webstarter Kit run gulp.serve:
----------------------------------------------------------------------------------------
C:\Users\Hans\web\google\wsk_054>gulp serve
[09:02:24] Using gulpfile ~\web\google\wsk_054\gulpfile.js
[09:02:24] Starting 'styles'...
[09:02:41] 'styles' all files 92.75 kB
[09:02:41] Finished 'styles' after 16 s
[09:02:41] Starting 'serve'...
[09:02:41] Finished 'serve' after 500 ms
[WSK] Local URL: http://localhost:3000
[WSK] External URL: http://192.168.178.21:3000
[WSK] Serving files from: .tmp
[WSK] Serving files from: app
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: spawn cmd ENOENT
    at exports._errnoException (util.js:746:11)
    at Process.ChildProcess._handle.onexit (child_process.js:1046:32)
    at child_process.js:1137:20
    at process._tickCallback (node.js:355:11)

C:\Users\Hans\web\google\wsk_054>

Webstarter Kit run gulp:
---------------------------------------------------------------------------------------
C:\Users\Hans\web\google\wsk_054>gulp
[09:03:56] Using gulpfile ~\web\google\wsk_054\gulpfile.js
[09:03:56] Starting 'clean'...
[09:03:56] Finished 'clean' after 16 ms
[09:03:56] Starting 'default'...
[09:03:56] Starting 'styles'...
[09:03:59] 'styles' all files 92.75 kB
[09:03:59] Finished 'styles' after 3.18 s
[09:03:59] Starting 'jshint'...
[09:04:02] Starting 'html'...
[09:04:17] Starting 'images'...
[09:04:23] Starting 'fonts'...
[09:04:23] Starting 'copy'...
[09:04:23] Finished 'jshint' after 24 s
[09:04:25] 'html' all files 44.25 kB
[09:04:25] Finished 'html' after 23 s
[09:04:25] 'copy' all files 48.88 kB
[09:04:25] Finished 'copy' after 1.44 s
[09:04:25] 'images' all files 18.55 kB
[09:04:25] Finished 'images' after 8.15 s
[09:04:25] 'fonts' all files 1.09 MB
[09:04:25] Finished 'fonts' after 1.93 s
[09:04:25] Finished 'default' after 29 s

------------------------------------------finish -----------------------------------------

**Comment by codeandrop** [comment] 2015-05-04 13:54
@HansS can you confirm your windows and gulp version?

**Comment by HansS** [comment] 2015-05-04 15:52
windows 8.1
gulp:       3.8.11

**Comment by RedHope** [comment] 2015-05-06 17:29
Same issue for me as well. Running windows 8.1, gulp 3.8.11, node 0.12.2 and npm 2.7.4

**Comment by enlightendev** [comment] 2015-05-13 12:30
same issue here running 'gulp serve' on windows; works fine on mac
------------------------------------------------------------------------------
[BS] Serving files from: dist
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: spawn cmd ENOENT
    at exports._errnoException (util.js:746:11)
    at Process.ChildProcess._handle.onexit (child_process.js:1053:32)
    at child_process.js:1144:20
    at process._tickCallback (node.js:355:11)
------------------------------------------------------------------------------
gulp --version
[08:20:35] CLI version 3.8.11
[08:20:35] Local version 3.8.11

npm --version
2.7.4

node --version
v0.12.2

**Comment by Garbee** [comment] 2015-05-13 15:04
Try node version 0.10. Some part of the workflow may require that version to operate due to changes in 0.11/0.12.

**Comment by stephan-nordnes-eriksen** [comment] 2015-07-02 01:16
I had similar issues. Try deleting your `npm_modules` and run `npm install` again. Solved my issue.

**Comment by jitendravyas** [comment] 2015-07-17 17:33
@stephan-nordnes-eriksen do you mean `node_module` folder ?

**Comment by stephan-nordnes-eriksen** [comment] 2015-07-21 17:34
yeah.. `node_modules`, sorry.

**Comment by codeandrop** [comment] 2015-07-24 15:11
Not sure if this can be considered close or needs further investigation

**Comment by perspektiveweb** [comment] 2015-07-26 18:00
I'm still having the issue.

Windows 7
Gulp 3.9.0

**Comment by codeandrop** [comment] 2015-07-27 13:32
Did you try @stephan-nordnes-eriksen solution? Also which node version do you have?

**Comment by perspektiveweb** [comment] 2015-07-27 13:36
Yes, I did that without success.

**Comment by sowings13** [comment] 2015-07-28 16:03
I experienced a similar issue when running a gulp task that compiled files into a directory and the files already existed from a previous run of the task.  Adding a clean function that removed the old files before running the regular task fixed my issue.

**Comment by codeandrop** [comment] 2015-07-31 21:21
@sowings13  There is already a command `gulp clean` you can run, let me know if it does the same thing.
@perspektiveweb can you try that command to see if it helps?

**Comment by perspektiveweb** [comment] 2015-08-01 00:43
Works for me now, thanks guys!

**Comment by codeandrop** [comment] 2015-08-01 01:29
@addyosmani I think with that solution you can close this

**Comment by Tsmith18256** [comment] 2015-08-06 04:02
I had this issue in the very beginning, too. For me, it was that I didn't know what gulp was so I had compiled the SCSS using Koala beforehand. After deleting the generated css and map files it worked fine.

**Closed** 2015-08-28 09:23 UTC
Labels: question

**Comment by Karl-EdwardFPJeanMehu** [comment] 2015-09-09 04:21
The same issue (events.js:85...) showed up for me. In my case, i narrowed the problem down to the gulp-uglify plugin i was using. Logging the error solve my problem like so:
...
.pipe(uglify())
.on('error', function(err){
    console.log(err)
})

Uglify emits the error events when it cannot minify a file. It turns out this can occur in the case of syntax errors as was in my case. 
ref:https://github.com/terinjokes/gulp-uglify/blob/4fa24c39bb74540da29d8d0fd1f98ca0bf947476/README.md

**Comment by quaintcow** [comment] 2015-10-22 21:46
I'm having this issue as well

**Comment by quaintcow** [comment] 2015-11-11 22:01
gulp clean didn't work
