### ISSUE TITLE
Footer collapse buttons are displayed on desktop browsers

### ISSUE THREAD

**Issue by forforeach** [google/web-starter-kit#797] opened 2015-12-18 14:00 UTC
Hi,
Browse to starter kit both from desktop and mobile device. On mobile, go to the footer of the page. Expand one of dropdown sections. Now look at the desktop browser and you'll see the collapse icon also displayed. 
Seems like a bug.

-----------------------------------------------------------------------------------------------------------
![Reproduction](http://i.giphy.com/d2YVP6aUjf5Ihg3K.gif)

**Comment by Bound3R** [comment] 2016-02-17 18:15
maybe it's a bug in material design lite version, check your error in this page [text-only template](http://www.getmdl.io/templates/text-only/index.html ) (almost the same template used in web-starter-kit) and report to be the case but in [MDL issues](https://github.com/google/material-design-lite/issues/).

I hope this helps :sweat_smile:

**Comment by surma** [comment] 2016-02-17 21:45
Thanks for the detailed report, @forforeach! It is bug, but in MDL as @Bound3R correctly states. It’s not immediately obvious, but it’s a duplicate of google/material-design-lite#1688. Closing this in favor of that issue :)

**Closed by surma** 2016-02-17 21:45 UTC
