### ISSUE TITLE
Scripts folder generated one level up from Project root

### ISSUE THREAD

**Issue by dspice** [google/web-starter-kit#848] opened 2016-03-01 11:49 UTC
Hi there, when I run the default gulp task from my project directory, a scripts folder with main.min.js within it is generated a folder level above the root of my project directory. Is this expected? Cheers.

**Comment by garyterry** [comment] 2016-03-03 10:21
I'm getting this as well... trying to find a fix now...

**Comment by MinnSoe** [comment] 2016-03-08 23:06
@dspice & @garyterry,

I've confirmed that this is happening and I have submitted a pull request with
a fix (PR #849). Hopefully, by chance, nothing was overridden in your parent
folders.

**Comment by neolwc** [comment] 2016-03-26 20:00
Same problem here @addyosmani

**Comment by Tempurturtul** [comment] 2016-05-19 21:48
Same here.

Would using a [custom block](https://github.com/jonkemp/useref#custom-blocks) be an acceptable solution?

**Comment by addyosmani** [comment] 2016-05-30 17:37
Hey folks (@neolwc, @MinnSoe, @garyterry). Sorry you ran into this issue. Before I merge in the suggested fix for this, could you confirm what OS you're running into this issue on? On OSX 10.11.4, the current behaviour does not appear to generate this file a few levels up but I'll wait on a confirm then work on reproducing.

**Comment by Tempurturtul** [comment] 2016-05-31 12:12
Occurs on Linux Mint 17.3 for me.

**Comment by addyosmani** [comment] 2016-05-31 12:54
Does the fix in https://github.com/MinnSoe/web-starter-kit/commit/bd3db1a52d0d4dd91390af3d4a0692cd45db463e address this for those that are running into this problem?

**Comment by Tempurturtul** [comment] 2016-06-02 12:24
It does here @addyosmani.

**Comment by MinnSoe** [comment] 2016-06-03 19:33
@addyosmani, I'm on OSX 10.11.5 and it looks like PR #853 on master works for me. @Tempurturtul, does master work for you on LM 17.3? I'm pretty sure it's good to close.

**Comment by Tempurturtul** [comment] 2016-06-03 21:36
@MinnSoe, master is working for me on LM 17.3 and on Ubuntu 14.04. I think it's good to close too.

**Comment by addyosmani** [comment] 2016-06-04 10:35
Awesome. Thanks everyone!

**Closed by addyosmani** 2016-06-04 10:35 UTC
