### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by panchowtf** [google/web-starter-kit#658] opened 2015-03-18 16:22 UTC
i have run 
npm install
then after instalation
i run $ gulp (the default function, with the very basic files) and i get a rang error after jshint starts.

**Comment by Garbee** [comment] 2015-03-18 16:55
Duplicate of issue #649

**Comment by addyosmani** [comment] 2015-03-21 13:29
Closing as a dupe.

**Closed by addyosmani** 2015-03-21 13:29 UTC
