### ISSUE TITLE
[Discussion] Next release

### ISSUE THREAD

**Issue by addyosmani** [google/web-starter-kit#940] opened 2017-05-23 21:55 UTC
It's been a while since we last tagged a release of WSK and much has changed in that time.

@jeffposnick @gauntface and I released Workbox as an evolution on sw-precache and toolbox. There's a PR switching WSK over to it in #937

@sgomes shipped Material Components Web with the Material Design team. It's unclear to me whether we should switch to using that over MDL for this project. I'd be interested in thoughts if folks have any strong opinions.

There's a backlog of PRs: https://github.com/google/web-starter-kit/pulls. Looking through some of them are additions I feel would detract from the simplicity of WSK while others like #933 look like they might be useful to bring in. 

I would also like to evaluate if we can find some new blood to help maintain WSK. Many of us are juggling other projects atm and would love any help we can get.

**Comment by Garbee** [comment] 2017-05-23 23:24
WSK should shift to MCW once it is in beta form at the earliest. It is currently Alpha stage so I'd urge against any work going into it at this time. MDL is effectively a low-maintained project as well at this point but still functions for what it was intended to do.

I agree that numerous PRs and requests people want are quite off-base for what WSK should provide. Especially the numerous ones wanting partial support baked in.

Honestly on the future overall. I feel like we don't need "yet another starter project" around. There are so many and it invites an immense amount of general support requests for getting things working how others want and within their projects. It makes just managing things more difficult which in itself is a big pressure. Perhaps the project could pivot in purpose. Refocus the project as an example of a simple base project that puts together the various offerings of high-priority projects from the Chrome team's people. Like Workbox and MCW. With the MCW shift that would include a webpack conversion, but that's fine to show how to include MCW into your own app. So WSK would be evolved into an integration sample over a generic starter kit.

**Comment by sgomes** [comment] 2017-05-30 10:45
Material Components for the web is generally of better quality than MDL already, with components being closer to spec, full support for RTL, better accessibility, and better development practices in general.

That said, as @Garbee pointed out, it's still alpha, which means that there can still be breaking changes. There may also be a few components missing, but the gap is closing rapidly.

So my suggestion would be to try to align the release schedules for WSK and MDC-Web; if WSK-next will only launch at a time when MDC-Web has become stable, it may be worth it to switch to it in the development branch already. Happy to put you in touch with the folks in charge of MDC-Web, but the project tracker is public anyway: https://www.pivotaltracker.com/n/projects/1664011

**Comment by gauntface** [comment] 2017-06-09 00:07
Personally I would like to shift WSK back to focusing on being a build process that developers can take and extend.

I'm not 100% sure pulling in web components will be a positive change - I imagine a lot of developers will just be confused.

I'm finding I'm moving my build processes more to NPM script for external tools that don't *need* to be in a build process (i.e. lint and mocha) and moving to web stardards where I can run the code in the browser without compilation (i.e. add a build process to transpile CSS variables instead of using Sass, Use multiple script tags using ES2015 and then transpile and merge files for dev).

**Comment by sgomes** [comment] 2017-06-09 12:08
@gauntface Just want to point out MDC-Web "components" aren't web components, rather just a more modular version of the same kind of "components" you find in MDL.

**Comment by lifeofbinary** [comment] 2017-10-25 11:05
This industry seriously needs regulating. HEAVILY.

We would have colonised Mars by now if all the tech types would only stop trying to make a square wheel. 

Its Linux(10^googolplex) messed up.

**Comment by gauntface** [comment] 2018-01-04 16:25
@Garbee would you be down for tackling an update of web-starter-kit with me this year?

Ideally I would like the tasks to be in a seperate files and just make it based on file extensions (i.e. .sass / .scss => Sass pipeline, .css => CSS pipeline, JS => browserify or rollup pipeline + lint).

I would like to drop the default use of material design lite and just be tasks.

cc @chrisdemars in case he'd be down for fiddling on some of this stuff (I feel like Bulp would be in a similar vane.

If general direction sounds appealing, I'm happy to put together a proposal doc.

**Comment by chrisdemars** [comment] 2018-01-06 00:06
I am down to help Matt.

**Comment by TheLarkInn** [comment] 2018-01-09 20:16
@gauntface, I commended in the GDOC which I'm sure you will see, but just in case, if you are going to use Rollup, you should state _why_ (and if it is meant to promote the use of `type=module`. 


At the moment, even Rich and our whole team recommend: webpack for apps, rollup for libs. https://medium.com/webpack/webpack-and-rollup-the-same-but-different-a41ad427058c

**Comment by TheLarkInn** [comment] 2018-01-09 20:19
AHHH Sorry Gaunty, I missed this comment: https://github.com/google/web-starter-kit/issues/880#issuecomment-356398446. 

Since perf is likely a key player/theme, I think it's likely a good idea to mention trade-off's of shipping modules natively + using rollup, (no code splitting, etc.).

**Comment by Garbee** [comment] 2018-01-10 20:20
Sorry @gauntface. I'd love to help out if this project is to continue, however I'm pretty deep in searching for a new job which is taking a good bit of time. So I don't know how much time I can actually dedicate to helping out regularly with forming PRs and getting the new pipeline setup. :frowning:

**Comment by gauntface** [comment] 2018-01-12 18:30
@TheLarkInn I'll be sure to tag you in to PR's for this stuff.

I'm largely just trying to make the flow easy to understand for everyone - Webpack does a lot for you and introduces magic as a result but would ❤️ a hand over story for developers wanting to move on to a process that does the above, how does that sound? @addyosmani for a check on whether this seems like an ok approach (given he's the current maintainer).

@Garbee totally understand and good luck with the job hunt!!

**Closed** 2020-07-25 07:11 UTC
