### ISSUE TITLE
ServiceWorker doesn't work in Firefox with Starter Kit OOTB

### ISSUE THREAD

**Issue by nhoizey** [google/web-starter-kit#860] opened 2016-05-03 12:47 UTC
I just downloaded the Starter Kit and ran `gulp serve:dist` and while the Service Worker works perfectly in Chrome stable, I get this error in Firefox stable console:

```
Error: Script terminated by timeout at:
debug@http://localhost:3001/scripts/sw/sw-toolbox.js:18:110
[12]</<@http://localhost:3001/scripts/sw/sw-toolbox.js:40:669
```

**Comment by addyosmani** [comment] 2016-05-30 17:52
Just checked latest against Firefox stable with master and I've confirmed the following errors are seen on `gulp serve:dist`:

<img width="1074" alt="screen shot 2016-05-30 at 18 41 19" src="https://cloud.githubusercontent.com/assets/110953/15655575/37f73b0a-2696-11e6-8a9f-f117ac56c32c.png">

After [updating](https://github.com/google/web-starter-kit/commit/722095f1ed333c9b8d35aa982abb47895fa3d938) WSK to the latest version of sw-precache (we were using an older version) and testing in Firefox Nightly, everything seems to work fine there. 

When I tested in Firefox stable post-update, I was still seeing a bug so it's a possibility this was a mix of two different issues. Could you verify this all works for you in FF Nightly?

cc @jeffposnick in case there's an issue I missed upstream (looked at the tracker but nothing obvious stood out).

**Comment by nhoizey** [comment] 2016-05-31 14:00
I still have the `TypeError` in Firefox Stable indeed.

I tried to install Firefox Developer Edition, but it broke my Firefox Stable, I lost a lot of open tabs. I will try to install Nightly instead, but I first have to find a way to recover all my data…

**Comment by jeffposnick** [comment] 2016-05-31 14:39
I can reproduce the issue in Firefox stable (46.0.1) but not in Nightly (49.0a1).

The code in question comes from `sw-toolbox`, and is in `caches.open()`, presumably to handle the runtime caching of the Google APIs/Fonts.

CC: @wibblymat and @gauntface in case they've heard of anything with Firefox 46 `sw-toolbox`, and CC: @wanderview who's been working on the Firefox Cache Storage implementation in case he know of any Firefox 46 issues that have since been fixed.

**Comment by wibblymat** [comment] 2016-05-31 15:48
I've not heard of anything, and not seen any issues raised on `sw-toolbox`.

I haven't reproduced the issue, but if the error is really being thrown by the `caches.open` call then perhaps check exactly what string is being passed into it - just to rule out the error being elsewhere.

**Comment by gauntface** [comment] 2016-05-31 16:54
Would be good to get a unit test on toolbox as well if anyone finds out the offending string

**Comment by wanderview** [comment] 2016-05-31 17:06
Trying to run this locally now to see if I can reproduce.

**Comment by wanderview** [comment] 2016-05-31 19:32
Ok, I think I understand whats happening here.

The problem is in FF46 and FF47 we don't gracefully handle this on first registration:

```
    navigator.serviceWorker.register('service-worker.js')
    .then(function(registration) {
      // Check to see if there's an updated version of service-worker.js with
      // new files to cache:
      // https://slightlyoff.github.io/ServiceWorker/spec/service_worker/index.html#service-worker-registration-update-method
      if (typeof registration.update === 'function') {
        registration.update();
      }
```

The update ends up stepping on the registration currently running and killing it.  This results in the service worker getting unregistered.

This is fixed in FF48+ by the implementation of the unified job queue:

  https://bugzilla.mozilla.org/show_bug.cgi?id=1256428

I think you can work around this bug by only calling update if there is a service worker already registered.  If `navigator.serviceWorker.get()` does not resolve to an existing registration then this is a first-time `register()` and `update()` is not needed.

**Comment by wanderview** [comment] 2016-05-31 19:34
> I tried to install Firefox Developer Edition, but it broke my Firefox Stable, I lost a lot of open tabs. I will try to install Nightly instead, but I first have to find a way to recover all my data…

Dev edition should use a separate profile by default.  I highly recommend using separate profiles for the different firefox release channels.

**Comment by wanderview** [comment] 2016-05-31 19:35
Of course, if the service worker is already registered, then you will get an update for free via navigation.  So you probably don't want to call `update()` at all here.

**Comment by jeffposnick** [comment] 2016-05-31 19:38
Thanks for digging in, @wanderview!

Yes, that explicit `registration.update();` isn't needed, and has already been [dropped elsewhere](https://github.com/GoogleChrome/sw-precache/pull/69). I'll file a PR to remove it from the WSK as well.

**Comment by wanderview** [comment] 2016-05-31 19:56
Incidentally this is really good at triggering this memory leak (fixed in FF47+):

https://bugzilla.mozilla.org/show_bug.cgi?id=1270161

**Closed** 2016-06-02 20:46 UTC
